dt_eng_proj:
  outputs:
    dev:
      catalog: adventureworkslt
      host: dbc-36e1263d-15a2.cloud.databricks.com
      http_path: /sql/1.0/warehouses/6aafc2aea4d091fc
      schema: saleslt_gold
      threads: 1
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      type: databricks
  target: dev
